# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.1
maven_group = net.zelythia
archives_name = tool_trinkets
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19.4
autotools_version = 3.4.0+1.19.4

# Fabric
fabric_loader_version = 0.18.4
fabric_api_version = 0.87.2+1.19.4

trinkets_version = 3.6.0

#Forge
forge_version = 1.19.4-45.4.0

curios_version = 1.19.4-5.1.5.4
