modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/zelythia/tool_trinkets/issues"
license = "MIT"

[[mods]]
modId = "tool_trinkets"
version = "${version}"
displayName = "Tool Trinkets"
displayURL = "https://modrinth.com/mod/tool_trinkets"
authors = "lukas/zelythia"
description = '''
This mod adds trinket slots for minecraft tools that also work with AutoTools!
'''
logoFile = "assets/tool_trinkets/icon.png"

[[dependencies.tool_trinkets]]
modId = "neoforge"
type="required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tool_trinkets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tool_trinkets]]
modId = "curios"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.tool_trinkets]]
modId = "autotools"
mandatory = false
versionRange = "[3.3.2,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "tool_trinkets.mixins.json"
